// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_hex`, `hex_val`, `to_hex`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Derive a real Ed25519 identity from a recovery mnemonic.
///
/// Deterministic: the same mnemonic always yields the same keypair, so the
/// mnemonic is a true backup/restore phrase.
Future<Identity> identityFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiIdentityFromMnemonic(mnemonic: mnemonic);

/// Recompute the Ed25519 public key from a hex private key (32 bytes).
Future<String> publicFromPrivate({required String privateKeyHex}) =>
    RustLib.instance.api
        .crateApiPublicFromPrivate(privateKeyHex: privateKeyHex);

/// Sign a UTF-8 message with a hex private key; returns the hex signature.
Future<String> signMessage(
        {required String privateKeyHex, required String message}) =>
    RustLib.instance.api
        .crateApiSignMessage(privateKeyHex: privateKeyHex, message: message);

/// A device identity: 32-byte Ed25519 private/public keys, hex-encoded.
class Identity {
  final String privateKeyHex;
  final String publicKeyHex;

  const Identity({
    required this.privateKeyHex,
    required this.publicKeyHex,
  });

  @override
  int get hashCode => privateKeyHex.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Identity &&
          runtimeType == other.runtimeType &&
          privateKeyHex == other.privateKeyHex &&
          publicKeyHex == other.publicKeyHex;
}
